"""Add payment details to Booking model

Revision ID: ba80e356eabf
Revises: ad580ed717d9
Create Date: 2024-12-26 17:37:24.815486

"""
from alembic import op
import sqlalchemy as sa
from datetime import datetime


# revision identifiers, used by Alembic.
revision = 'ba80e356eabf'
down_revision = 'ad580ed717d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))

    # Set default values for existing rows
    op.execute("UPDATE booking SET payment_date = CURRENT_TIMESTAMP, amount_paid = 0.0")

    # Alter columns to be non-nullable
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.alter_column('payment_date', existing_type=sa.DateTime(), nullable=False)
        batch_op.alter_column('amount_paid', existing_type=sa.Float(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('amount_paid')
        batch_op.drop_column('payment_date')
    # ### end Alembic commands ###